
// <auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PROFiLiX.Web.Migrations
{
    /// <inheritdoc />
    public partial class Profilix : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "EUCProfileBuddyTask");

            migrationBuilder.CreateTable(
                name: "ProfilixTask",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    UserName = table.Column<string>(type: "TEXT", nullable: false),
                    TaskName = table.Column<string>(type: "TEXT", nullable: false),
                    TaskExecuted = table.Column<DateTime>(type: "TEXT", nullable: false),
                    TaskState = table.Column<int>(type: "INTEGER", nullable: false),
                    TaskRunTime = table.Column<TimeSpan>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ProfilixTask", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ProfilixTask");

            migrationBuilder.CreateTable(
                name: "EUCProfileBuddyTask",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    TaskExecuted = table.Column<DateTime>(type: "TEXT", nullable: false),
                    TaskName = table.Column<string>(type: "TEXT", nullable: false),
                    TaskRunTime = table.Column<TimeSpan>(type: "TEXT", nullable: false),
                    TaskState = table.Column<int>(type: "INTEGER", nullable: false),
                    UserName = table.Column<string>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_EUCProfileBuddyTask", x => x.Id);
                });
        }
    }
}
